version: "3"
services:
    bootnode:
        build: .
        ports:
            - "30301:30301/udp"
    geth:
        depends_on:
            - bootnode
        image: polyswarm/priv-testnet
        ports:
            - "30303:30303"
            - "8545:8545"
        command: ["--nodiscover", "--bootnodes", "enode://591b0aeb292f1a7513e83b19acb08c482822609215da3637198240b04557332437746a63c27afd6df424b6430e987613f125a7e843443bbb61a4001d4a9058c0@0.0.0.0:30301", "--maxpeers", "0", "--syncmode", "full", "--networkid", "1337", "--targetgaslimit", "94000000", "--rpc", "--rpcvhosts", "localhost,geth", "--rpcaddr", "0.0.0.0", "--rpcapi", "eth,web3,personal,net", "--ws", "--wsaddr", "0.0.0.0", "--wsapi", "eth,web3,personal,net", "--wsorigins", "*", "--unlock", "4b1867c484871926109e3c47668d5c0938ca3527,d87e4662653042c5da11711542c11f2c8433612d,4f10166cafd7856ea946124927d4478fdd18d979,f0243d9b2e332d7072dd4b143a881b3f135f380c,f870491ea0f53f67846eecb57855284d8270284d,34e583cf9c1789c3141538eec77d9f0b8f7e89f2,2b813f079e7e3cf24eeb1ac5853bd6f9118a04ea,1215242c8f0eff0a4ac06ea3d73caa78279fb9bb,05328f171b8c1463eafdacca478d9ee6a1d923f8,085ba02c35555fecb8147820135fdfec10eed85a", "--password", "password.txt", "--mine"]
    sidechain:
        image: polyswarm/priv-testnet
        ports:
            - "30304:30303"
            - "7545:8545"
        command: ["--nodiscover", "--maxpeers", "0", "--syncmode", "full", "--networkid", "1337", "--targetgaslimit", "94000000", "--rpc", "--rpcvhosts", "localhost,sidechain", "--rpcaddr", "0.0.0.0", "--rpcapi", "eth,web3,personal,net", "--ws", "--wsaddr", "0.0.0.0", "--wsapi", "eth,web3,personal,net", "--wsorigins", "*", "--unlock", "4b1867c484871926109e3c47668d5c0938ca3527,d87e4662653042c5da11711542c11f2c8433612d,4f10166cafd7856ea946124927d4478fdd18d979,f0243d9b2e332d7072dd4b143a881b3f135f380c,f870491ea0f53f67846eecb57855284d8270284d,34e583cf9c1789c3141538eec77d9f0b8f7e89f2,2b813f079e7e3cf24eeb1ac5853bd6f9118a04ea,1215242c8f0eff0a4ac06ea3d73caa78279fb9bb,05328f171b8c1463eafdacca478d9ee6a1d923f8,085ba02c35555fecb8147820135fdfec10eed85a", "--password", "password.txt", "--mine"]
    polyswarmd:
        image: "polyswarm/polyswarmd"
        depends_on:
            - geth
            - ipfs
            - contract
        environment:
            - PYTHONUNBUFFERED=1
            - HOME_ETH_URI=http://geth:8545
            - SIDE_ETH_URI=http://sidechain:8545
            - IPFS_URI=http://ipfs:5001
        ports:
            - "31337:31337"
        command: ["./scripts/wait_for_truffle.sh", "polyswarmd"]
        volumes:
            - "contracts:/etc/polyswarmd"
    contract:
        depends_on:
            - geth
            - sidechain
            - ipfs
        image: "polyswarm/contractor"
        environment:
            - geth=geth
            - HOME_CHAIN=http://geth:8545
            - SIDE_CHAIN=http://sidechain:8545
            - IPFS="http://ipfs:5001"
        volumes:
            - "contracts:/build"
    ambassador:
        image: "polyswarm/ambassador"
        depends_on:
            - polyswarmd
        environment:
            - AMBASSADOR_HOST=http://ambassador:342
            - POLYSWARM_HOST=http://polyswarmd:31337
        restart: always
    # arbiter_verbatim:
    #     image: "polyswarm/arbiter-verbatim"
    #     depends_on:
    #         - polyswarmd
    #     environment:
    #         - ARBITER_HOST=http://arbiter_verbatim:352
    #         - POLYSWARM_HOST=http://polyswarmd:31337
    ipfs:
        image: "ipfs/go-ipfs"
        environment:
            - IPFS_BIND_IP=0.0.0.0
        ports:
            - "4001:4001"
        volumes:
            - "ipfs-export:/export"
            - "ipfs-data:/data/ipfs"
volumes:
    contracts:
        driver_opts:
            type: none
            device: /root/contracts
            o: bind
    ipfs-export:
    ipfs-data: