version: "3"
services:
    homechain:
        image: polyswarm/priv-testnet
        ports:
            - "30303:30303"
            - "8545:8545"
        command: ["--nodiscover", "--maxpeers", "0", "--syncmode", "full", "--networkid", "1337", "--targetgaslimit", "94000000", "--rpc", "--rpcvhosts", "localhost,homechain", "--rpcaddr", "0.0.0.0", "--rpcapi", "eth,web3,personal,net", "--ws", "--wsaddr", "0.0.0.0", "--wsapi", "eth,web3,personal,net", "--wsorigins", "*", "--unlock", "4b1867c484871926109e3c47668d5c0938ca3527,d87e4662653042c5da11711542c11f2c8433612d,4f10166cafd7856ea946124927d4478fdd18d979,f0243d9b2e332d7072dd4b143a881b3f135f380c,f870491ea0f53f67846eecb57855284d8270284d,34e583cf9c1789c3141538eec77d9f0b8f7e89f2,2b813f079e7e3cf24eeb1ac5853bd6f9118a04ea,1215242c8f0eff0a4ac06ea3d73caa78279fb9bb,05328f171b8c1463eafdacca478d9ee6a1d923f8,085ba02c35555fecb8147820135fdfec10eed85a", "--password", "password.txt", "--mine", "--gasprice", "0"]
    sidechain:
        image: polyswarm/priv-testnet
        ports:
            - "30304:30303"
            - "7545:8545"
        command: ["--nodiscover", "--maxpeers", "0", "--syncmode", "full", "--networkid", "1337", "--targetgaslimit", "94000000", "--rpc", "--rpcvhosts", "localhost,sidechain", "--rpcaddr", "0.0.0.0", "--rpcapi", "eth,web3,personal,net", "--ws", "--wsaddr", "0.0.0.0", "--wsapi", "eth,web3,personal,net", "--wsorigins", "*", "--unlock", "4b1867c484871926109e3c47668d5c0938ca3527,d87e4662653042c5da11711542c11f2c8433612d,4f10166cafd7856ea946124927d4478fdd18d979,f0243d9b2e332d7072dd4b143a881b3f135f380c,f870491ea0f53f67846eecb57855284d8270284d,34e583cf9c1789c3141538eec77d9f0b8f7e89f2,2b813f079e7e3cf24eeb1ac5853bd6f9118a04ea,1215242c8f0eff0a4ac06ea3d73caa78279fb9bb,05328f171b8c1463eafdacca478d9ee6a1d923f8,085ba02c35555fecb8147820135fdfec10eed85a", "--password", "password.txt", "--mine", "--gasprice", "0"]
    polyswarmd:
        image: "polyswarm/polyswarmd"
        depends_on:
            - homechain
            - ipfs
            - contracts
        environment:
            - PYTHONUNBUFFERED=1
            - HOME_ETH_URI=http://homechain:8545
            - SIDE_ETH_URI=http://sidechain:8545
            - IPFS_URI=http://ipfs:5001
        ports:
            - "31337:31337"
        command: ["./scripts/wait_for_truffle.sh", "polyswarmd"]
        volumes:
            - "contracts:/etc/polyswarmd"
    contracts:
        depends_on:
            - homechain
            - sidechain
            - ipfs
        image: "polyswarm/contracts"
        environment:
            - geth=homechain
            - HOME_CHAIN=http://homechain:8545
            - SIDE_CHAIN=http://sidechain:8545
            - IPFS=http://ipfs:5001
            - OPTIONS=/config/users.yml
        volumes:
            - "contracts:/build"
            - "./config:/config"
    ipfs:
        image: "ipfs/go-ipfs"
        environment:
            - IPFS_BIND_IP=0.0.0.0
        ports:
            - "4001:4001"
        volumes:
            - "ipfs-export:/export"
            - "ipfs-data:/data/ipfs"
    ambassador:
        image: "polyswarm/ambassador"
        depends_on:
          - polyswarmd
        environment:
          - POLYSWARMD_HOST=polyswarmd
          - POLYSWARMD_PORT=31337
        command: "./wait_and_run.sh"
        restart: always
    microengine:
        image: "polyswarm/microengine"
        depends_on:
          - polyswarmd
        environment:
          - POLYSWARMD_HOST=polyswarmd
          - POLYSWARMD_PORT=31337
          - POLYSWARMD_ADDR=polyswarmd:31337
        command: "./scripts/wait_and_test.sh"
    arbiter-tester:
        build:
            dockerfile: e2e/arbiter.test.Dockerfile
            context: ../
        depends_on:
          - polyswarmd
        environment:
          - PYTHONUNBUFFERED=1
          - POLYSWARMD_HOST=polyswarmd
          - POLYSWARMD_PORT=31337
          - TIMEOUT=600
          - TEST_ARBITER=0xf870491ea0f53f67846eecb57855284d8270284d
        command: "./scripts/wait_and_run.sh"
volumes:
    contracts:
        driver_opts:
                type: none
                device: /root/contracts
                o: bind
    ipfs-export:
    ipfs-data:
